-- seed: animals
DELETE FROM animals;
DELETE FROM sqlite_sequence WHERE name = 'animals';

INSERT INTO animals (id, name, species, species_slug, age, genetics, genetics_profile, origin, special_notes, description, image_path, owner_id, is_private, is_showcased, is_piebald, created_at) VALUES
    (1, 'Solaris', 'Bartagame', 'pogona-vitticeps', '2021-05', 'Hypo Citrus het Translucent', '{"genes":{"hypo-citrus":"heterozygous","translucent":"heterozygous"}}', 'Nachzucht 2021', 'Regelmäßige Gewichtskontrolle alle zwei Wochen.', 'Liebt üppig bepflanzte Becken und reagiert positiv auf Target-Training.', 'uploads/animals/solaris.jpg', NULL, 0, 1, 0, '2024-01-05 08:00:00'),
    (2, 'Nebula', 'Bartagame', 'pogona-vitticeps', '2022-08', 'Zero het Translucent', '{"genes":{"zero":"homozygous","translucent":"heterozygous"}}', 'Eigene Nachzuchtlinie', 'Benötigt höhere UVB-Dosis, tägliche Werte werden geloggt.', 'Sehr ruhiges Tier, ideal für Schulungszwecke.', 'uploads/animals/nebula.jpg', NULL, 0, 1, 0, '2024-01-05 08:05:00'),
    (3, 'Aurelia', 'Bartagame', 'pogona-vitticeps', '2020', 'Hypo Citrus', '{"genes":{"hypo-citrus":"homozygous"}}', 'Übernahme aus Partnerprojekt', 'Regeneration nach Schwanzspitze überwacht.', 'Aktiv im Tageslicht, nimmt Futter aus der Hand.', 'uploads/animals/aurelia.jpg', NULL, 0, 0, 0, '2024-01-05 08:10:00'),
    (4, 'Caspian', 'Hakennasennatter', 'heterodon-nasicus', '2021-10', 'Arctic Conda 100% het Toffee Belly', '{"genes":{"arctic":"heterozygous","conda":"heterozygous","toffee-belly":"heterozygous"}}', 'Nachzucht 2021', 'Sehr futtermotiviert, benötigt enge Boxen während Häutung.', 'Ruhiges Handling, reagiert auf Klicktraining.', 'uploads/animals/caspian.jpg', NULL, 0, 1, 0, '2024-01-05 08:15:00'),
    (5, 'Lyra', 'Hakennasennatter', 'heterodon-nasicus', '2023-03', 'Super Arctic', '{"genes":{"arctic":"homozygous"}}', 'Eigenes Brutprojekt 2023', 'Wird aktuell auf Froschschenkel umgestellt.', 'Zeigt ausgeprägtes Farbspiel nach Temperaturwechsel.', 'uploads/animals/lyra.jpg', NULL, 0, 1, 0, '2024-01-05 08:20:00'),
    (6, 'Vector', 'Hakennasennatter', 'heterodon-nasicus', '2020', 'Axanthic Conda het Toffee Belly', '{"genes":{"conda":"heterozygous","toffee-belly":"heterozygous"}}', 'Langzeitprojekt', 'Regelmäßige Rachitis-Prophylaxe dokumentieren.', 'Hat erfolgreiche Live-Demos für Workshops absolviert.', 'uploads/animals/vector.jpg', NULL, 0, 0, 0, '2024-01-05 08:25:00'),
    (7, 'Quantum', 'Königspython', 'python-regius', '2021-07', 'Pastel Clown het Desert Ghost', '{"genes":{"pastel":"heterozygous","clown":"homozygous","desert-ghost":"heterozygous"}}', 'Import 2022', 'Braucht leicht erhöhte Luftfeuchte im Winter.', 'Perfekter Kandidat für DG-Clown-Projekt 2024.', 'uploads/animals/quantum.jpg', NULL, 0, 1, 0, '2024-01-05 08:30:00'),
    (8, 'Echo', 'Königspython', 'python-regius', '2019', 'Pastel Desert Ghost', '{"genes":{"pastel":"heterozygous","desert-ghost":"homozygous"}}', 'Eigenbestand', 'Frisst zuverlässig Frostfutter, Tracking in App.', 'Besonders klare Farben, beliebtes Ausstellungstier.', 'uploads/animals/echo.jpg', NULL, 0, 1, 0, '2024-01-05 08:35:00'),
    (9, 'Nimbus', 'Königspython', 'python-regius', '2018', 'Clown het Desert Ghost', '{"genes":{"clown":"homozygous","desert-ghost":"heterozygous"}}', 'Projekt Clown/DG', 'Braucht größere Verstecke, nutzt RFID-Tracking.', 'Wird für Morphanalyse-Videos eingesetzt.', 'uploads/animals/nimbus.jpg', NULL, 0, 0, 0, '2024-01-05 08:40:00'),
    (10, 'Pixel', 'Leopardgecko', 'eublepharis-macularius', '2022-05', 'White & Yellow Tangerine', '{"genes":{"white-and-yellow":"heterozygous"}}', 'Nachzucht 2022', 'Spezielle UV-Intervalle werden protokolliert.', 'Sehr neugierig, nutzt interaktive Futterstation.', 'uploads/animals/pixel.jpg', NULL, 0, 1, 0, '2024-01-05 08:45:00'),
    (11, 'Nova', 'Leopardgecko', 'eublepharis-macularius', '2021', 'Eclipse Tangerine', '{"genes":{"eclipse":"heterozygous"}}', 'Community-Abgabe 2023', 'Langsam steigende Gewichtskurve dokumentieren.', 'Zeigt farbintensives Pattern in der Paarungssaison.', 'uploads/animals/nova.jpg', NULL, 0, 0, 0, '2024-01-05 08:50:00'),
    (12, 'Atlas', 'Leopardgecko', 'eublepharis-macularius', '2019', 'White & Yellow Super Tang', '{"genes":{"white-and-yellow":"homozygous"}}', 'Foundation Tier', 'Verkürzt Ruhephase im Winter, Temperaturprotokoll beachten.', 'Aktiver Zuchterfolg mit mehreren Clutchen dokumentiert.', 'uploads/animals/atlas.jpg', NULL, 0, 1, 0, '2024-01-05 08:55:00'),
    (13, 'Sora', 'Grüner Baumpython', 'morelia-viridis', '2020', 'Biak Blue', '{"lineage":"biak-blue"}', 'Biak-Linie 2020', 'Empfindlich gegenüber Lautstärke – Ruhezone markiert.', 'Farbverlauf wird monatlich fotografisch festgehalten.', 'uploads/animals/sora.jpg', NULL, 0, 1, 0, '2024-01-05 09:00:00'),
    (14, 'Halo', 'Grüner Baumpython', 'morelia-viridis', '2018', 'Aru White', '{"lineage":"aru-white"}', 'Aru-Linie', 'Wird in Zuchtplanung 2024 berücksichtigt.', 'Zeigt starkes Weiß am Kopf, beliebt für Fotoserien.', 'uploads/animals/halo.jpg', NULL, 0, 0, 0, '2024-01-05 09:05:00'),
    (15, 'Marble', 'Kornnatter', 'pantherophis-guttatus', '2022-04', 'Miami het Anery', '{"genes":{"miami":"line","anery":"heterozygous"}}', 'Co-Op Projekt', 'Temperaturkurve für Farbentwicklung wird geteilt.', 'Extrem kontrastreicher Nachwuchs wird erwartet.', 'uploads/animals/marble.jpg', NULL, 0, 1, 0, '2024-01-05 09:10:00'),
    (16, 'Glacier', 'Kornnatter', 'pantherophis-guttatus', '2021-02', 'Anery Scaleless', '{"genes":{"anery":"homozygous","scaleless":"homozygous"}}', 'Scaleless-Projekt', 'Benötigt feuchte Verstecke zur Häutung.', 'Hautpflege wird mit Aloe-Spray dokumentiert.', 'uploads/animals/glacier.jpg', NULL, 0, 1, 1, '2024-01-05 09:15:00'),
    (17, 'Pulse', 'Blauzungenskink', 'tiliqua-scincoides', '2019', 'Sunset Linie', '{"lineage":"sunset"}', 'Australien-Import', 'Routine-Blutbilder für Projektstudie aufnehmen.', 'Sehr zahm, reagiert auf Clickertraining.', 'uploads/animals/pulse.jpg', NULL, 0, 0, 0, '2024-01-05 09:20:00'),
    (18, 'Grimm', 'Blauzungenskink', 'tiliqua-scincoides', '2020', 'Axanthic', '{"genes":{"axanthic-scincoides":"homozygous"}}', 'Nachzucht 2020', 'Benötigt UVB-Intensität über 150 µW/cm².', 'Besonderes Projekt zur Analyse von Pigmentverlust.', 'uploads/animals/grimm.jpg', NULL, 0, 1, 0, '2024-01-05 09:25:00'),
    (19, 'Ember', 'Stachelschwanzwaran', 'varanus-acanthurus', '2017', 'Red Ridge', '{"lineage":"red-ridge"}', 'Langzeitpflege', 'Wird für Bioacoustic-Studie genutzt.', 'Aktive Grabphase, Terrarium wurde erweitert.', 'uploads/animals/ember.jpg', NULL, 0, 0, 0, '2024-01-05 09:30:00'),
    (20, 'NovaLux', 'Königsnatter', 'lampropeltis-triangulum', '2023-06', 'Nelsoni', '{"genes":{"nelsoni":"homozygous"}}', 'Nelsoni-Projekt', 'Regelmäßige Fotodokumentation für Farbentwicklung.', 'Zeigt ruhiges Wesen, ideal für Workshops.', 'uploads/animals/novalux.jpg', NULL, 0, 1, 0, '2024-01-05 09:35:00');
-- end
